# Generated by Django 4.1.4 on 2023-01-19 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('snum', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('deptid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptlocation', models.CharField(max_length=15)),
                ('deptid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
